import "reflect-metadata";
import { DataSource } from "typeorm";
import {
	User,
	Address,
	Branch,
	Business,
	City,
	Contact,
	Country,
	Email,
	Employee,
	Inventory,
	Nationality,
	Operation,
	Permission,
	Person,
	Product,
	State,
} from "./models/pg";
import { config } from "./config/config";

export const AppDataSource = new DataSource({
	type: config.SQLITE.type,
	// host: config.POSTGRESQL.host,
	// port: config.POSTGRESQL.port,
	// username: config.POSTGRESQL.user,
	// password: config.POSTGRESQL.password,
	database: config.SQLITE.database, // config.POSTGRESQL.dbName,
	synchronize: false,
	logging: true,
	entities: [
        User,
        Address,
        Branch,
        Business,
        City,
        Contact,
        Country,
        Email,
        Employee,
        Inventory,
        Nationality,
        Operation,
        Permission,
        Person,
        Product,
        State,
    ],
	migrations: [],
	subscribers: [],
});
