import "reflect-metadata";
import { DataSource } from "typeorm";
import {
	User,
	Address,
	Branch,
	Business,
	City,
	Contact,
	Country,
	Email,
	Employee,
	Inventory,
	Nationality,
	Operation,
	Permission,
	Person,
	Product,
	State,
} from "./models/pg";
import { config } from "./config/config";

export const AppDataSource = new DataSource({
	type: config.DB.type,
	host: config.DB.host,
	port: config.DB.port,
	username: config.DB.user,
	password: config.DB.password,
	database: config.DB.dbName,
	synchronize: false,
	logging: true,
	entities: [
        User,
        Address,
        Branch,
        Business,
        City,
        Contact,
        Country,
        Email,
        Employee,
        Inventory,
        Nationality,
        Operation,
        Permission,
        Person,
        Product,
        State,
    ],
	migrations: [],
	subscribers: [],
});
